config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :carts
  resources :products
  resources :venues
  resources :backbars
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/backbar.rb
class Backbar < ApplicationRecord
  belongs_to :venue
end

app/controllers/backbars_controller.rb
class BackbarsController < ApplicationController
  before_action :set_backbar, only: [:show, :edit, :update, :destroy]

  # GET /backbars
  # GET /backbars.json
  def index
    @backbars = Backbar.all
  end

  # GET /backbars/1
  # GET /backbars/1.json
  def show
  end

  # GET /backbars/new
  def new
    @backbar = Backbar.new
  end

  # GET /backbars/1/edit
  def edit
  end

  # POST /backbars
  # POST /backbars.json
  def create
    @backbar = Backbar.new(backbar_params)

    respond_to do |format|
      if @backbar.save
        format.html { redirect_to @backbar, notice: 'Backbar was successfully created.' }
        format.json { render :show, status: :created, location: @backbar }
      else
        format.html { render :new }
        format.json { render json: @backbar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /backbars/1
  # PATCH/PUT /backbars/1.json
  def update
    respond_to do |format|
      if @backbar.update(backbar_params)
        format.html { redirect_to @backbar, notice: 'Backbar was successfully updated.' }
        format.json { render :show, status: :ok, location: @backbar }
      else
        format.html { render :edit }
        format.json { render json: @backbar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /backbars/1
  # DELETE /backbars/1.json
  def destroy
    @backbar.destroy
    respond_to do |format|
      format.html { redirect_to backbars_url, notice: 'Backbar was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_backbar
      @backbar = Backbar.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def backbar_params
      params.require(:backbar).permit(:venue_id, :product_id, :price)
    end
end

app/helpers/backbars_helper.rb
module BackbarsHelper
end

app/views/backbars/_form.html.erb
<%= form_for(backbar) do |f| %>
  <% if backbar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(backbar.errors.count, "error") %> prohibited this backbar from being saved:</h2>

      <ul>
      <% backbar.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :venue_id %>
    <%= f.number_field :venue_id %>
  </div>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.number_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/backbars/edit.html.erb
<h1>Editing Backbar</h1>

<%= render 'form', backbar: @backbar %>

<%= link_to 'Show', @backbar %> |
<%= link_to 'Back', backbars_path %>

app/views/backbars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Backbars</h1>

<table>
  <thead>
    <tr>
      <th>Venue</th>
      <th>Product</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @backbars.each do |backbar| %>
      <tr>
        <td><%= backbar.venue_id %></td>
        <td><%= backbar.product_id %></td>
        <td><%= backbar.price %></td>
        <td><%= link_to 'Show', backbar %></td>
        <td><%= link_to 'Edit', edit_backbar_path(backbar) %></td>
        <td><%= link_to 'Destroy', backbar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Backbar', new_backbar_path %>

app/views/backbars/new.html.erb
<h1>New Backbar</h1>

<%= render 'form', backbar: @backbar %>

<%= link_to 'Back', backbars_path %>

app/views/backbars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Venue:</strong>
  <%= @backbar.venue_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @backbar.product_id %>
</p>

<p>
  <strong>Price:</strong>
  <%= @backbar.price %>
</p>

<%= link_to 'Edit', edit_backbar_path(@backbar) %> |
<%= link_to 'Back', backbars_path %>